{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.gpc",
    "module": "fields",
    "version": "6.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fields-6.0.0-SNAPSHOT-plain.jar",
          "url": "fields-6.0.0-SNAPSHOT-plain.jar",
          "size": 131221,
          "sha512": "c3164e21ea39e8c438d9f6c5470ba88e5b002a2c278c78ba87f528350e592f8240feba6f9e44b624415b22929b9934a4fe8d7e5563773170bf0bdc3620890c51",
          "sha256": "03153e31b54f49239dc2b6af6c423437a3b2ab451f8d7697bebcaafbe886cfb0",
          "sha1": "2543a8d376e46457adcfd8dde22c293c833a21f6",
          "md5": "0e6ea78dd27558b3e34fdff05aec8ccc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.grails",
          "module": "scaffolding-core",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fields-6.0.0-SNAPSHOT-plain.jar",
          "url": "fields-6.0.0-SNAPSHOT-plain.jar",
          "size": 131221,
          "sha512": "c3164e21ea39e8c438d9f6c5470ba88e5b002a2c278c78ba87f528350e592f8240feba6f9e44b624415b22929b9934a4fe8d7e5563773170bf0bdc3620890c51",
          "sha256": "03153e31b54f49239dc2b6af6c423437a3b2ab451f8d7697bebcaafbe886cfb0",
          "sha1": "2543a8d376e46457adcfd8dde22c293c833a21f6",
          "md5": "0e6ea78dd27558b3e34fdff05aec8ccc"
        }
      ]
    }
  ]
}
